#!/bin/bash
# ---------------------------
#===============================================================
# CLUSTER BITS
#===============================================================
#PBS -N ICECAV
#PBS -l select=3
#PBS -l walltime=01:20:00
#PBS -A n01-ORCHESTRA
#PBS -j oe
#PBS -r n

# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR

# Set the number of threads to 1
#   This prevents any system libraries from automatically 
#   using threading.
export OMP_NUM_THREADS=1
# Change to the directory that the job was submitted from
ulimit -s unlimited

export NEMOproc=48
export XIOSproc=1

#===============================================================
# LAUNCH JOB
#===============================================================
echo `date` : Launch Job
touch stdouterr
rm namelist_cfg domain_cfg.nc
ln -s NAMELISTcfg/namelist_cfg.zps namelist_cfg
ln -s DOMAINcfg/domain_cfg_zps_3D.nc domain_cfg.nc
aprun -b -n $NEMOproc -N 24 ./nemo_cold   >&  stdouterr_nemo : -N 1 -n $XIOSproc ./xios_server.exe >&  stdouterr_xios
chmod a+r *
#cp run.stat run.stat.cold_zps
exit
